export interface IFoodItem {
  id: number;
  ean_id?: string;
  name: string;
  brand?: string;
  image_url?: string;
  calories: number;
  g_protein: number;
  g_carbs: number;
  g_fats: number;
  g_fiber?: number;
  serving_quantity?: number;
  serving_unit?: string;
  is_quick_add?: boolean;
}

export interface ICreateFoodItem {
  ean_id?: string;
  name: string;
  brand?: string;
  image_url?: string;
  calories: number;
  g_protein: number;
  g_carbs: number;
  g_fats: number;
  g_fiber?: number;
  serving_quantity?: number;
  serving_unit?: string;
  is_quick_add?: boolean;
}

export interface ILogEntry {
  food_item_id: number;
  log_serving: number;
  date: string;
  profile_id: number;
}

export interface ILogEntryWithFoodItem {
  id: number;
  food_item_id: number;
  log_serving: number;
  date: string;
  ean_id?: string;
  name: string;
  brand?: string;
  image_url?: string;
  calories: number;
  g_protein: number;
  g_carbs: number;
  g_fats: number;
  g_fiber?: number;
  serving_quantity?: number;
  serving_unit?: string;
  is_quick_add?: boolean;
}

export interface IQuickAdd {
  id?: number; // Optional, as it's auto-generated by the DB
  log_entry_id: number;
  name: string;
  calories: number;
  g_protein: number;
  g_carbs: number;
  g_fats: number;
  date: string;
}

export interface IProfile {
  id: number;
  name: string;
  background: string;
  calorie_goal: number;
  protein_goal: number;
  fat_goal: number;
  carb_goal: number;
}
